apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense         # Name of your EKS cluster
  region: us-west-1           # AWS region where the cluster will be created
  version: v1  

managedNodeGroups:
- name: expense
  instanceType: m5.large
  desiredCapacity: 3
  spot: true    