apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-cluster         # Name of your EKS cluster
  region: us-east-1           # AWS region where the cluster will be created
managedNodeGroups:
- name: expense
  instanceType: m5.large
  desiredCapacity: 3
  spot: true  

  